services:
  app:
    container_name: movie-backend-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_PORT=5000
      - DATABASE_URL=DATABASE_URL
      - TOKEN_SECRET_KEY=TOKEN_SECRET_KEY
    ports:
      - 5000:5000
    depends_on:
      - nosql-db
      - rabbitmq
  
  nosql-db:
    image: mvertes/alpine-mongo
    ports:
      - 27018:27017
    container_name: nosql-db
    volumes:
      - ./db/:/data/db
  
  rabbitmq:
    image: rabbitmq:alpine
    container_name: rabbitmq
    ports:
      - 5672:5672